log:
  level: DEBUG
providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/config
api:
  insecure: true
  debug: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

experimental:
  plugins:
    jwt:
      moduleName: github.com/agilezebra/jwt-middleware
      version: v1.2.6
