providers:
  docker: {}
  file:
    directory: /etc/traefik/config
api:
  insecure: true
  debug: true
experimental:
  plugins:
    jwt:
      moduleName: github.com/agilezebra/jwt-middleware
      version: v1.2.6
