http:
  middlewares:
    secure-api:
      plugin:
        jwt:
          issuers:
            - https://keycloak.traefik.me/realms/playground
          insecureSkipVerify:
            - keycloak.traefik.me
          require:
            aud: account
